config/routes.rb
Rails.application.routes.draw do
  scope '/', controller: :error_pages do
    get 'error_404'
    get 'unauthorized'
  end

  resources :articles
  resources :comments, path: '/articles/comments'
  resources :recipes
  resources :user_groups

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  resources :users

  root to: 'visitors#index'
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :users
end

app/controllers/admin/user_groups_controller.rb
class Admin::UserGroupsController < Admin::BaseController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    size = 3
    page = params[:page].to_i || 0
    @pages = (UserGroup.all.size.to_f / size.to_f).ceil - 1
    @user_groups = UserGroup.all[page * size, size]
  end

  # GET /users/1
  def show
    @user_group = UserGroup.find(params[:id])
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to admin_user_group_url(@user_group), notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to admin_user_group_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user_group
    @user_group = UserGroup.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_group_params
    params.require(:user_group).permit(:name, :level)
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController

  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    size = APP_CONFIG["element_per_page"]
    page = params[:page].to_i || 0
    @pages = (UserGroup.all.size.to_f / size.to_f).ceil - 1
    @user_groups = UserGroup.all[page * size, size]
  end

  # GET /users/1
  def show
    @users = @user_group.users.all
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        BaseEntity.all.each do |base_entity|
          right = Right.new
          right.user_group_id = @user_group.id
          right.base_entity_id = base_entity.id
          right.right_create = false
          right.right_read = false
          right.right_update_self = false
          right.right_update_lesser_group = false
          right.right_update_actual_group = false
          right.right_update_upper_group = false
          right.right_update_self = false
          right.right_delete_self = false
          right.right_delete_lesser_group = false
          right.right_delete_actual_group = false
          right.right_delete_upper_group = false
          right.save
        end

        format.html { redirect_to edit_user_group_url(@user_group), notice: 'User group was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to edit_user_group_url(@user_group), notice: 'User group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /user_groups/1
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_group
    @user_group = UserGroup.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_group_params
    params.require(:user_group).permit(:name, :level, rights_attributes:
        [:id, :right_create, :right_read, :right_update_self, :right_update_lesser_group, :right_update_actual_group, :right_update_upper_group, :right_delete_self, :right_delete_lesser_group, :right_delete_actual_group, :right_delete_upper_group]
    )
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :level %>
  <%= f.number_field :level %>
</div>

<table class="table table-condensed table-bordered table-hover">
  <thead>
  <tr>
    <th class="text-center">Entity</th>
    <th class="text-center">Create</th>
    <th class="text-center">Read</th>
    <th class="text-center">Update Self</th>
    <th class="text-center">Update Lesser Group</th>
    <th class="text-center">Update Actual Group</th>
    <th class="text-center">Update Upper Group</th>
    <th class="text-center">Delete Self</th>
    <th class="text-center">Delete Lesser Group</th>
    <th class="text-center">Delete Actual Group</th>
    <th class="text-center">Delete Upper Group</th>
  </tr>
  </thead>
  <tbody>
  <%= f.fields_for :rights, @user_group.rights do |right| %>
      <tr>
        <td><%= right.object.base_entity.singular %></td>
        <td><%= right.check_box :right_create %></td>
        <td><%= right.check_box :right_read %></td>
        <td><%= right.check_box :right_update_self %></td>
        <td><%= right.check_box :right_update_lesser_group %></td>
        <td><%= right.check_box :right_update_actual_group %></td>
        <td><%= right.check_box :right_update_upper_group %></td>
        <td><%= right.check_box :right_delete_self %></td>
        <td><%= right.check_box :right_delete_lesser_group %></td>
        <td><%= right.check_box :right_delete_actual_group %></td>
        <td><%= right.check_box :right_delete_upper_group %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="actions">
  <%= f.submit %>
</div>

app/views/user_groups/_user_group.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <div class="caption">
      <h3><%= link_to user_group.name, user_group_path(user_group) %></h3>
      <h6><%= user_group.level %></h6>
      <p>
        <% if has_rights?('user_group', 'edit') %>
            <%= link_to 'Edit', edit_user_group_path(user_group), class: 'btn btn-primary' %>
        <% end %>
        <% if has_rights?('user_group', 'destroy') %>
            <%= link_to 'Destroy', user_group_path(user_group), method: :delete, class: 'btn btn-primary' %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/user_groups/_user_groups.html.erb
<div class="row">
  <%= render @user_groups %>
</div>
<% if !local_assigns[:pagination].nil? && pagination && @pages > 0 %>
    <nav aria-label="...">
      <ul class="pagination">
        <% if params[:page].to_i == 0 %>
            <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
        <% else %>
            <li>
              <%= link_to user_groups_path(page: params[:page].to_i - 1) do %>
                  <span aria-hidden="true">&laquo;</span>
              <% end %>
            </li>
        <% end %>
        <% for i in 0..@pages %>
            <li class="<%= params[:page].to_i == i ? 'active' : '' %>">
              <%= link_to i + 1, user_groups_path(page: i) %></a>
            </li>
        <% end %>
        <% if params[:page].to_i == @pages %>
            <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
        <% else %>
            <li>
              <%= link_to user_groups_path(page: params[:page].to_i + 1) do %>
                  <span aria-hidden="true">&raquo;</span>
              <% end %>
            </li>
        <% end %>
      </ul>
    </nav>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing User Group</h1>

<%= form_for @user_group, url: user_group_path(@user_group), method: :put do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
<% end %>

<%= link_to 'Show', user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User groups</h1>

<%= render partial: 'user_groups', locals: {pagination: true} %>

<% if has_rights?('user_group', 'new') %>
    <%= link_to 'New', new_user_group_path %>
<% end %>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

<%= form_for @user_group, url: user_groups_path, method: :post do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
<% end %>


<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @user_group.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @user_group.level %>
</p>

<ul>
  <% @users.each do |user| %>
    <li><%= user.full_name %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>