config/routes.rb
Rails.application.routes.draw do
  scope '/', controller: :error_pages do
    get 'error_404'
    get 'unauthorized'
  end

  resources :articles
  resources :comments, path: '/articles/comments'
  resources :recipes
  resources :user_groups

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  resources :users

  root to: 'visitors#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  helper_method :has_rights?

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  def index
    size = APP_CONFIG["element_per_page"]
    page = params[:page].to_i || 0
    @pages = (Recipe.all.size.to_f / size.to_f).ceil - 1
    @recipes = Recipe.all[page * size, size]
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /recipes/1
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
    end
  end

  def has_rights?(entity, action, id = nil)
    if !current_user.nil?
      entity_query = BaseEntity.where(:singular => entity).or(BaseEntity.where(:plural => entity)).first
      if !entity_query.nil?
        entity_id = entity_query.id
        if !entity_id.nil?
          right = Right.where(:user_group_id => current_user.user_group_id, :base_entity_id => entity_id).first
          if (id.nil? and params[:id].nil?) ^ entity != 'recipe'
            case action
              when 'new', 'create'
                return right.right_create
              when 'index', 'show'
                return right.right_read
            end
          else
            recipe = Recipe.find((id.nil? ? params[:id] : id))
            case action
              when 'edit', 'update'
                if recipe.user_id == current_user.id
                  return right.right_update_self
                else
                  if recipe.user.user_group_id == current_user.user_group_id
                    return right.right_update_actual_group
                  else
                    if recipe.user.user_group.level > current_user.user_group.level
                      return right.right_update_upper_group
                    else
                      return right.right_update_lesser_group
                    end
                  end
                end
              when 'destroy'
                if recipe.user_id == current_user.id
                  return right.right_delete_self
                else
                  if recipe.user.user_group_id == current_user.user_group_id
                    return right.right_delete_actual_group
                  else
                    if recipe.user.user_group.level > current_user.user_group.level
                      return right.right_delete_upper_group
                    else
                      return right.right_delete_lesser_group
                    end
                  end
                end
            end
          end
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="field">
  <%= f.label :user_id %>
  <%= current_user.full_name %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

app/views/recipes/_recipe.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <img src="..." alt="...">
    <div class="caption">
      <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
      <h6><%= recipe.user.full_name %></h6>
      <p>
        <% if has_rights?('recipe', 'edit', recipe.id) %>
            <%= link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-primary' %>
        <% end %>
        <% if has_rights?('recipe', 'destroy', recipe.id) %>
            <%= link_to 'Destroy', recipe_path(recipe), method: :delete, class: 'btn btn-primary' %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/recipes/_recipes.html.erb
<div class="row">
  <%= render @recipes %>
</div>
<% if !local_assigns[:pagination].nil? && pagination && @pages > 0 %>
    <nav aria-label="...">
      <ul class="pagination">
        <% if params[:page].to_i == 0 %>
            <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
        <% else %>
            <li>
              <%= link_to recipes_path(page: params[:page].to_i - 1) do %>
                  <span aria-hidden="true">&laquo;</span>
              <% end %>
            </li>
        <% end %>
        <% for i in 0..@pages %>
            <li class="<%= params[:page].to_i == i ? 'active' : '' %>">
              <%= link_to i + 1, recipes_path(page: i) %></a>
            </li>
        <% end %>
        <% if params[:page].to_i == @pages %>
            <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
        <% else %>
            <li>
              <%= link_to recipes_path(page: params[:page].to_i + 1) do %>
                  <span aria-hidden="true">&raquo;</span>
              <% end %>
            </li>
        <% end %>
      </ul>
    </nav>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= form_for @recipe, url: recipe_path(@recipe), method: :put do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
<% end %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<%= render partial: "recipes/recipes", locals: {pagination: true} %>

<% if has_rights?('recipe', 'new') %>
    <%= link_to "New", new_recipe_path %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= form_for @recipe, url: recipes_path, method: :post do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
<% end %>


<% if has_rights?('recipe', 'index') %>
<%= link_to 'Back', recipes_path %>
<% end %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipe.user %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>